const BAD_REQUEST_CODE = 400;
const DEFAULT_ERROR_CODE = 500;
const NOT_FOUND = 404;
const CONFLICT = 409;
const INCORRECT_CREDENTIALS = 401;
const FORBIDDEN = 403;

module.exports = {
  BAD_REQUEST_CODE,
  DEFAULT_ERROR_CODE,
  NOT_FOUND,
  CONFLICT,
  INCORRECT_CREDENTIALS,
  FORBIDDEN,
};
